### DISCUSSION TITLE
[分享]自定义CSS样式：将输入栏固定在页面上方

### DISCUSSION THREAD

**Discussion by moulai** [usememos/memos#1260] [Show and tell]
```CSS
.page-wrapper.home>.page-container>.memos-wrapper {
	height: 100vh;
	max-height: 100vh;
}
```
非常简陋，原理不明。
于v0.11.0版本测试通过。
