### DISCUSSION TITLE
修改热力图颜色

### DISCUSSION THREAD

**Discussion by Juskinbo** [usememos/memos#1274] [Q&A] [answered]
如题，假如我想通过自定义CSS样式修改热力图颜色，该如何修改？

**Comment by Wujiao233** [comment, marked as answer]
Try this
```css
.stat-day-l1-bg{
    background-color: rgba(255, 208, 243, 1) !important
}
.stat-day-l2-bg{
    background-color: rgba(255, 150, 228, 1) !important
}
.stat-day-l3-bg{
    background-color: rgba(255, 85, 212, 1) !important
}
.stat-day-l4-bg{
    background-color: rgba(190, 0, 141, 1) !important
}
```
just for example, this color scheme is not good...
