### DISCUSSION TITLE
Better design for the todo items

### DISCUSSION THREAD

**Discussion by ksdme** [usememos/memos#1670] [General]
The default design for the todo items looks out of place and isn't too indicative either. So, I ended up styling it to look like this.
![image](https://github.com/usememos/memos/assets/12156014/f04e1db0-a56a-4952-9056-bd4e88f6e03a)

If you like it, you can use the following `Settings > System > Additional Style` to get it.
```css
span.todo-block.done + span {
  text-decoration: line-through;
}

span.todo-block.done {
  color: lightseagreen;
  background: lightseagreen;
  border-color: lightseagreen;
}
```
