### DISCUSSION TITLE
How to disable telemetry ("metric" parameter)

### DISCUSSION THREAD

**Discussion by DHBytes** [usememos/memos#2655] [Q&A]
I am self hosting Memos using Docker and I want to disable any telemetry data sent to Memos.
According to the [self-hosting documentation](https://www.usememos.com/docs/install/self-hosting), it can be disabled by setting the `--metric` parameter to `false`.

This is my docker compose:
```
version: "3.0"
services:
  memos:
    image: ghcr.io/usememos/memos:latest
    container_name: memos
    volumes:
      - ~/apps/memos/:/var/opt/memos
    ports:
      - 5230:5230
    command:
      - "metric=false"
```

However, it's being ignored and the logs show that the metric parameter is "true":
```
---
Server profile
data: /var/opt/memos
dsn: /var/opt/memos/memos_prod.db
addr: 
port: 5230
mode: prod
driver: sqlite
version: 0.18.1

metric: true
---
Version 0.18.1 has been started on port 5230
👉Website: https://usememos.com
███╗   ███╗███████╗███╗   ███╗ ██████╗ ███████╗
████╗ ████║██╔════╝████╗ ████║██╔═══██╗██╔════╝
👉GitHub: https://github.com/usememos/memos
██╔████╔██║█████╗  ██╔████╔██║██║   ██║███████╗
██║╚██╔╝██║██╔══╝  ██║╚██╔╝██║██║   ██║╚════██║
██║ ╚═╝ ██║███████╗██║ ╚═╝ ██║╚██████╔╝███████║
╚═╝     ╚═╝╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝
---
```

Is my docker compose syntax wrong (I am not good at Docker)? How can I disable all telemetry and metrics from being collected? Thanks!

(By the way, data collection should be opt-in not opt-out, especially since Memos site states it is a "privacy-first" service. Come on, guys!)
