### DISCUSSION TITLE
[分享] 自定义CSS：标签样式、字体大小、选项卡隐藏等

### DISCUSSION THREAD

**Discussion by moulai** [usememos/memos#2845] [Show and tell]
```css
/* 修改特殊字体颜色 */
.text-blue-600 {
    --tw-text-opacity: 1;
    color: rgb(11 96 176 / var(--tw-text-opacity));
}

/* 修改标签样式 */
.dark .inline-block {
    border: 1px solid rgb(110,110,110);
    border-radius: 8px;
    background-color: rgb(90, 90, 90);
    padding: 0px 4px;
}

.inline-block {
    border: 1px solid rgb(230,230,230);
    border-radius: 8px;
    background-color: rgb(245, 245, 245);
    padding: 0px 4px;
}

/* 修改Memo字号 */
.memo-wrapper .text-base {
    font-size: 0.95rem;
}

/* 修改代码块字号 */
.text-sm {
    font-size: 0.85rem;
}

/* 隐藏 通知 选项卡 */
#header-inbox {
  display: none;
}

/* 隐藏 个人资料 选项卡 */
#header-profile {
  display: none;
}

/* 隐藏 探索 选项卡 */
#header-explore {
  display: none;
}

/* 修改编辑器字体为等宽 */
textarea {
    font-family: 'Courier New', Courier, monospace;
}
```
已于v0.19.0测试通过。

**Comment by i-iooi-i** [comment]
大佬，标签样式貌似在 v0.20版本 已经不适用啦~

**Reply by zhouyaxiong** [reply]
0.22版本标签的设置也不生效了

**Comment by i-iooi-i** [comment]
刷新了一下页面，就好了 😂😂 感谢🫡

**Comment by junevin1** [comment]
v0.22版本的字体大小不起效果。

**Comment by asasn** [comment]
大佬，0.22.5怎么实现各级标题大小啊，h1，h2，h3之类单独设置

**Reply by mimiqdev** [reply]
```
/* 修改H1字号 */
.text-5xl {
    font-size: 1.8rem;
}
/* 修改H2字号 */
.text-3xl {
    font-size: 1.5rem;
}
/* 修改H3字号 */
.text-xl {
    font-size: 1.2rem;
}
/* 修改H4字号 */
.text-lg {
    font-size: 1.1rem;
}
```
v0.23.0测试可以修改标题大小
修改前：
![image](https://github.com/user-attachments/assets/ac022bc6-734d-4f86-9867-a77c532889b6)
修改后：
![image](https://github.com/user-attachments/assets/a8dd606e-3ef7-4ed5-ae7d-d307a4de3303)

**Comment by moulai** [comment]
```css
/* 修改标签样式 */
.dark .inline-block {
    border: 1px solid rgb(110,110,110);
    border-radius: 8px;
    background-color: rgb(90, 90, 90);
    padding: 0px 4px;
}

.inline-block {
    border: 1px solid rgb(230,230,230);
    border-radius: 8px;
    background-color: rgb(245, 245, 245);
    padding: 0px 4px;
}

/* 修改Memo字号 */
.text-base {
    font-size: 1rem;
}

/* 修改代码块字号 */
.text-sm {
    font-size: 0.875rem;
}

/* 隐藏 通知 选项卡 */
#header-inbox {
  display: none;
}

/* 隐藏 个人资料 选项卡 */
#header-profile {
  display: none;
}

/* 隐藏 探索 选项卡 */
#header-explore {
  display: none;
}
```
0.22.4版本测试通过，但是超链接的字体大小暂未设置。
