### DISCUSSION TITLE
Wait for database to be ready

### DISCUSSION THREAD

**Discussion by malantp** [usememos/memos#4774] [Q&A] [answered]
I use a Docker compose file with a Postgres database and every time I reboot my system, Memos is crashing because it loads faster than the database, forcing me to restart it manually. Is there a way to prevent this?

**Comment by boojack** [comment]
Use `depends_on` to make applications wait for Postgres. https://docs.docker.com/compose/how-tos/startup-order/

**Reply by malantp** [reply, marked as answer]
That's what I've done but it was not enough, I needed to add a healthcheck on postgres. Thanks for the lead though!
If anyone need it, this is a solution:

On Postgres:
```yaml
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
```
On Memos:
```yaml
   depends_on:
      name_of_the_postgres_containter:
        condition: service_healthy
```
