### DISCUSSION TITLE
「分享」一些自定义 CSS

### DISCUSSION THREAD

**Discussion by YuJianghao** [usememos/memos#510] [Show and tell]
等宽字体
```css
.common-editor-inputer{font-family: consolas monospace;}
```
<img width="641" alt="image" src="https://user-images.githubusercontent.com/17293034/202988997-07dbb15b-13ad-4584-9acc-6003c7a47f96.png">

---

tag 样式
```css
.tag-span{background-color: rgb(37 99 235 / 0.15);padding: 0 5px;border-radius: 3px;font-size: small;line-height: 1.5;}
```
<img width="648" alt="image" src="https://user-images.githubusercontent.com/17293034/202989117-ad05f47e-c1c9-4c06-b26f-e4c0bbf394eb.png">
