### DISCUSSION TITLE
往下滑动的时候，可否隐藏编辑框？

### DISCUSSION THREAD

**Discussion by jeechoul** [usememos/memos#594] [Ideas]
我在往下滑动页面的时候表示想看内容，或者寻找内容，编辑框一直保持固定，会占用很大一部分空间，观看体验不是很好，大家觉得呢？

**Comment by YuJianghao** [comment]
好主意

**Comment by boojack** [comment]
或许可以通过自定义 CSS 样式来实现你需要的自定义。

**Comment by loudtell** [comment]
自定义css如下，可以实现你想要的效果。
```CSS
.page-wrapper.home>.page-container>.memos-wrapper>.memos-editor-wrapper {
    position: static !important;
}
.section-header-container, .memos-header-container {
    position: static !important;
}
```

> 我在往下滑动页面的时候表示想看内容，或者寻找内容，编辑框一直保持固定，会占用很大一部分空间，观看体验不是很好，大家觉得呢？
