### DISCUSSION TITLE
自定义样式分享：加载「霞鹜文楷」在线字体

### DISCUSSION THREAD

**Discussion by lmm214** [usememos/memos#977] [Ideas]
```css
body{font-family: "LXGW WenKai Screen", sans-serif !important;}
```

```javascript
function changeFont() { 
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.type = "text/css";
  link.href = "https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/lxgwwenkaiscreen.css";
  document.head.append(link);
};
changeFont()
```
