### ISSUE TITLE
Could not deploy to fly.io with the latest docker.io image

### ISSUE THREAD

**Issue by waynexia** [usememos/memos#1005]
### Describe the bug

My fly.io config:

```shell
➜  memos-fly cat fly.toml -p

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "neosmemo/memos:latest"

[env]
  DB_PATH = "/var/opt/memos/memos_prod.db"
```

Result with `flyctl deploy`:
```shell
➜  memos-fly flyctl deploy
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'neosmemo/memos:latest' remotely...
Error failed to fetch an image or build from source: Could not find image "docker.io/neosmemo/memos:latest"
```

I searched through fly.io document and get this post: https://community.fly.io/t/deploying-to-fly-via-github-action-failing/10171/19, which proposes to add those "with version" lines to CI build job:
```yml
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
```

### Steps to reproduce

`flyctl deploy` with `image = "neosmemo/memos:latest"`. The toml file above is trimmed, I'd like to provide the full version if needed.
