### ISSUE TITLE
Wrong order of typefaces in the font fallback list

### ISSUE THREAD

**Issue by chengluyu** [usememos/memos#1495]
### Describe the bug

The alphabets look weird and gross, because the font fallback list has a wrong order. Here is the CSS fragment I got from the source code.

```css
html,
body {
  @apply text-base w-full h-full dark:bg-zinc-800;
  font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Noto Sans", "Noto Sans CJK SC", "Microsoft YaHei UI", "Microsoft YaHei",
    "WenQuanYi Micro Hei", sans-serif, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol",
    "Noto Color Emoji";
}
```

You should place the Chinese fonts before the English fonts to avoid ugly alphabetic characters. [Reference](https://liam.page/2015/04/30/using-font-fallback-to-enhance-the-appreance-on-windows/)

### Steps to reproduce

No need to reproduce.
