### ISSUE TITLE
所有使用同名但不同内容的图片都被替换成同一张了

### ISSUE THREAD

**Issue by HuntZou** [usememos/memos#1632]
### Describe the bug

一觉醒来，发现所有使用Snipaste粘贴的图片都变成同一张图片，没注意是不是之前就这样还是今天突然才这样的。我怀疑是和图片名称有关，这些图片名称是一样的。

### Steps to reproduce

1. 使用Snipaste随便截图粘贴到memo输入框（Snipaste粘贴的每张图片名称都是一样的）
2. 待图片上传完成后检查resource
3. 以前的图片有一定几率被替换了

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/26397504/236082133-f49669f0-7bbd-4489-8628-92667284a672.png)

**Comment by HuntZou** [comment]
![image](https://user-images.githubusercontent.com/26397504/236085288-cdf32eca-82f5-4ae6-857a-11d7460c6e66.png)

![image](https://user-images.githubusercontent.com/26397504/236085373-e9ba56d5-a2d8-426b-ab72-fa6d5df16091.png)

**Comment by HuntZou** [comment]
不是概率性的，是同名的文件一定会被替换，之前认为是概率性的是因为浏览器缓存的原因。但是如果使用截图工具粘贴的图片，上传时名称一定是一样的，如何解决？

**Comment by CorrectRoadH** [comment]
🤔 我觉得如果memos在上传图片时遇到同名文件，在名称后面加一个后缀比如`xxx (1).png`、`xxx (2).png`，或许是一个好解决方案。

**Comment by Jonnyan404** [comment]
以下所述均基于 0.12.2 版本.
如果是SQLite存储呢,展示和存储不依赖名称,所以不存在这个情况. 过往版本曾经有这个Bug,建议升级.
如果是本地存储呢,在0.12.2版本中预置了`时间戳+文件名` 的格式,所以也不会有这个问题.
如果是云存储,未具体使用,不太清楚,如果有问题,在memos软件层面无解,建议你使用 Chrome扩展上传或者粘贴.

---

另外截止 2023-05-03 的代码里,本地存储的预置值没了,如果检测你未设置本地存储格式,默认存回SQLite.

**Comment by HuntZou** [comment]
使用的最新版本的docker镜像，版本为 v0.12.2

**Comment by HuntZou** [comment]
> 以下所述均基于 0.12.2 版本. 如果是SQLite存储呢,展示和存储不依赖名称,所以不存在这个情况. 过往版本曾经有这个Bug,建议升级. 如果是本地存储呢,在0.12.2版本中预置了`时间戳+文件名` 的格式,所以也不会有这个问题. 如果是云存储,未具体使用,不太清楚,如果有问题,在memos软件层面无解,建议你使用 Chrome扩展上传或者粘贴.
> 
> 另外截止 2023-05-03 的代码里,本地存储的预置值没了,如果检测你未设置本地存储格式,默认存回SQLite.

使用的最新版本的docker镜像，版本为 v0.12.2，以下为docker-compose.yml
```
version: "3.0"
services:
  memos:
    image: jonnyan404/memos:latest
    container_name: memos
    restart: unless-stopped
    volumes:
      - xxxxx/volumes/memos:/var/opt/memos
    ports:
      - 5230:5230
```
