### ISSUE TITLE
v0.13.0 在树莓派上部署后，memos显示时间不对

### ISSUE THREAD

**Issue by leafney** [usememos/memos#1726]
### Describe the bug

Using the latest image arm/v7 `v0.13.0` after Raspberry Pi deployment, the creation time is displayed incorrectly

### Steps to reproduce

docker-compose.yaml
```
version: "3.0"
services:
  memos:
    image: neosmemo/memos:0.13.0
    container_name: memos
    restart: unless-stopped
    volumes:
      - ./data/:/var/opt/memos
    ports:
      - 5230:5230
```

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/11624677/7bebc6ec-1c2a-4fb8-9480-8524a55fc5db)

**Comment by GodMeowIceSun** [comment]
建议尝试部署环境系统时间

**Comment by GodMeowIceSun** [comment]
建议尝试检查部署环境系统时间

**Comment by leafney** [comment]
> The host must have date and time set-up correctly. Use a ntp server to keep host time accurate.
> 
> Try to specify the timezone manually and point the host localtime to the container, like this:
> 
> ```yaml
> version: "3.0"
> services:
>   memos:
>     image: neosmemo/memos:0.13.0
>     container_name: memos
>     restart: unless-stopped
>     environment:
>       - TZ=Asia/Shanghai
>     volumes:
>       - /etc/localtime:/etc/localtime:ro
>       - ./data/:/var/opt/memos
>     ports:
>       - 5230:5230
> ```
> 
> Note that the displayed date is formatted by the browser in use, not the server. You can test using another browser and/or changing memos language and refreshing the page to check if the date is shown correctly.
> 
> Also, you may use Alt+Click over the date to change it and check if, somehow, this fixes the display.

@lincolnthalles  Thank you for your reply, but I tried this way, the result is still wrong. I have also run the linux/amd64 docker image, but it is normal.

**Comment by lincolnthalles** [comment]
> 
It seems you are not the only one having this issue.

Unfortunately, I don't own a Pi or other ARM SBC to help investigating this.

**_Important question_: This issue affects every created memo or only the sample memos?**

It would be helpful to confirm if the memo table is being populated with proper unix timestamps.

The values in those database columns must be something like "1684156803" (2023-05-15 10:20:03), which can be converted to a readable date and time this way:

```bash
# Linux bash
date +"%Y-%m-%d %H:%M:%S" -d @1684156803
```

```powershell
# Windows PowerShell
[System.DateTimeOffset]::FromUnixTimeSeconds(1684156803).DateTime
```

### Confirming the container date is current

```bash
sudo docker exec -it memos date
```
This should output something like "2023-05-15 19:40:03"

### Inspecting memo created and updated timestamps in the database

```bash
# Run this in the docker host to get a shell inside the container
sudo docker exec -it memos /bin/sh
# The shell prompt should become "/usr/local/memos"

# install SQLite shell
apk add sqlite

# load memos database in sqlite shell
sqlite3 /var/opt/memos/memos_prod.db

# inside the sqlite shell (sqlite> prompt):
SELECT id, created_ts, updated_ts FROM memo;
```
The output should be in this format:
![image](https://github.com/usememos/memos/assets/7476810/9ae3a2f1-425d-4b58-9c14-c4d494581d03)

If the output format is different, it means the database is being populated incorrectly and that would be a good lead to developers sort the issue.

**Comment by leafney** [comment]
@lincolnthalles Thank you for your reply. All created memo time displays are wrong. But now I don't have time to explore the specific cause of the error, I will try to look at the source code on the weekend.

**Comment by leafney** [comment]
@gabstehr  You are correct.
You mentioned `libseccomp2` reminds me of the problem that the container cannot start when using the node-red v2.x version of the container image, which is also caused by `libseccomp2`.

In addition to the solution you gave, I also thought of another : use `--security-opt=seccomp=unconfined`

```
version: "3.0"
services:
  memos:
    image: neosmemo/memos:0.13.0
    container_name: memos
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./data/:/var/opt/memos
    ports:
      - 5230:5230
```

After running it is normal time, except for the first default memo.

![image](https://github.com/usememos/memos/assets/11624677/2cd99b33-f75c-4428-8a78-35e2c4c13167)
