### ISSUE TITLE
create access token with NEVER expiration will expire immediately

### ISSUE THREAD

**Issue by zhaoyibo** [usememos/memos#2228]
### Describe the bug

When I create an access token with NEVER expiration, it will be expired immediately.

### Steps to reproduce

1. create an access token
2. Expiration choose NEVER

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/11988080/4b8194bf-6555-4a77-b864-b934e67935d6)
![image](https://github.com/usememos/memos/assets/11988080/e505c86f-b56e-417d-a38c-08b7057ef494)
![image](https://github.com/usememos/memos/assets/11988080/68a72dc0-8250-4879-80ad-eb8aafcd6198)

**Comment by boojack** [comment]
I cannot reproduce in the [demo site](https://demo.usememos.com). 

https://github.com/usememos/memos/assets/24653555/700b86dd-3ccc-4a92-894a-2ed670c2279c

**Comment by zhaoyibo** [comment]
I tried to create access token via admin account, but got the same thing.

https://github.com/usememos/memos/assets/11988080/8633cfd4-b2df-4d27-a66b-c70129b843f6

I just updated the memos from [v0.14.4](https://github.com/usememos/memos/releases/tag/v0.14.4) to [v0.15.0](https://github.com/usememos/memos/releases/tag/v0.15.0) today, and I use docker-compose bellow

```yaml
version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    restart: always
    volumes:
      - /MyDockerData/memos/:/var/opt/memos
    ports:
      - 5230:5230
    networks:
      - my-dockers-network

networks:
  my-dockers-network:
    external: true
```

I have no idea how to debug it.

Also, I found that it creates a new access token every time I log in.

https://github.com/usememos/memos/assets/11988080/90e4da21-d837-4473-ae90-e0e6d383496f
