### ISSUE TITLE
Failed to create user

### ISSUE THREAD

**Issue by stundenblume** [usememos/memos#2298]
### Describe the bug

I´m on a fresh install with the first user.
If I try to create a second user (user: testuser, password: password), I get the message "Failed to create user"

### Steps to reproduce

settings - member
fill username & password - click `create`

### Screenshots or additional context

Docker Log:

`2023-09-27T07:15:17Z method=POST uri=/memos.api.v2.UserService/ListUserAccessTokens status=200 error=
2023-09-27T07:15:19Z method=GET uri=/api/v1/user status=200 error=
2023-09-27T07:15:32Z method=POST uri=/api/v1/user status=500 error=code=500, message=Failed to create user, internal=constraint failed: NOT NULL constraint failed: user.open_id (1299)
2023-09-27T07:15:32Z method=GET uri=/api/v1/user status=200 error=`

**Comment by boojack** [comment]
Which version are you using?

**Comment by stundenblume** [comment]
v0.15.2
but I had the same behavior in v0.15.1

**Comment by stundenblume** [comment]
I should have written "nearly fresh install".
I already hat some momos written.

If I install a new container, log in, go straight to member. I can create new members without error.

I will have a look what is different between the nearly fresh and a really fresh install.

**Comment by stundenblume** [comment]
This is how I start MEMOS as Portainer stack.
```
version: '3'

services:
  memos:
    image: ghcr.io/usememos/memos:0.15
    container_name: memos
    hostname: memos
    network_mode: bridge
    restart: unless-stopped # always
    
    ports:
      - '5230:5230'

    volumes:
      - data:/var/opt/memos

volumes:
  data:
```

If I'm the only one, I will delete everything and copy the existing momos to a new container.
