### ISSUE TITLE
0.16.0 Unused resources removed from "Resources" page are not acturally deleted from local filesystem

### ISSUE THREAD

**Issue by sulisu** [usememos/memos#2383]
### Describe the bug

Unused resources removed from "Resources" page are not acturally deleted from local filesystem

### Steps to reproduce

1. Create a memo with a jpg file as attachment
2. In linux system console, check the jpg file is uploaded to local file system in memodata/assets folder.
3. In web page, delete the memo just created, then go to the Resource page.
4. The jpg file is showed in Unused resources category, remove it with the trashbin icon, conform the allert popup.
5. In linux system console, check the memodata/assets folder, the file is still in the folder.

### Screenshots or additional context

Enironment and setting:
docker container
object storage: local file system

docker-compose.yaml
```
version: "3.0"
services:
  memos:
    image: neosmemo/memos:0.16.0
    container_name: memos
    volumes:
      - ./memosdata/:/var/opt/memos
    ports:
      - 5230:5230
```

I can conform that it works in 0.14.4, I have not used 0.15.x beacuse it can not handle unused resource.
