### ISSUE TITLE
Custom CSS configurations for :after and :before selectors are lost when download image in sharing dialog.

### ISSUE THREAD

**Issue by Vespa314** [usememos/memos#2493]
### Describe the bug

in memos:
![image](https://github.com/usememos/memos/assets/6339395/48120bca-37b6-48f6-8e4a-c903fdae6be7)

here is the image after download:
![image](https://github.com/usememos/memos/assets/6339395/a5d0ade6-9113-48ba-8f4f-ed2873d69f6f)

### Steps to reproduce

for example: 
```css
.tag-span {
    background: #16A34A;
    position: relative;
    padding: 3px 5px 3px 5px;
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
    margin: 0 15px 0 0;
    line-height: 1;
}

.tag-span:after {
    border: 9.5px solid;
    border-color: transparent transparent transparent #16A34A;
    position: absolute;
    right: -18px;
    top: 0;
    content: "";
}
```
