### ISSUE TITLE
where are my memos being stored? SQLite database is not updating

### ISSUE THREAD

**Issue by shankargopal** [usememos/memos#2526]
### Describe the bug

This is not quite a bug, but I am really confused by it. I have been using the SQLite storage method.  My `docker-compose.yml` is provided in "additional context" below. 

I have, according to Memos' own display, 131 notes. This is correct. But if I run `sqlite3 memos_prod.db` on my system, the `memo` table has only 127 records and does not include my four latest notes.  The same applies if I access the sqlite database  using any other method, for instance, via Python. 

This didn't used to happen until I had to reinstall memos recently.  Earlier the sqlite database had all my notes.  I restored from a backup database and all the old notes show up in Memos. But I can't find where the new ones are being stored.  

This is important to me because I have been trying to keep backups of my notes database. But my backup methods all fail because the database is out of date.   I tried switching to "Local storage" in settings, but this seemed to make no difference - no new files were created that I could find in either the directory mounted as a volume on `/var/opt/memos` or in the working directory.  The SQlite database continues to not be updated.

Where are my notes being stored? It seems like magic! :-)

### Steps to reproduce

1. Install Memos using the `docker-compose.yml` filed provided here, modified to point to the correct storage directory.
2. Restore the database from an old copy.   
3. Access Memos and save some additional notes in it.  
4. Notes will not appear in the sqlite database.

### Screenshots or additional context

Contents of `docker-compose.yaml`:

```
version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - /mnt/pistorage/media/memos:/var/opt/memos
    ports:
      - 5230:5230
    restart: always
```
