### ISSUE TITLE
Can't access to data base file

### ISSUE THREAD

**Issue by steam3d** [usememos/memos#2549]
### Describe the bug

I use self-hosting doc. The folder where stores files does not exitst.
https://www.usememos.com/docs/install/self-hosting

```
ubuntu@ubuntu-vb:~$ cd ~/.memos
bash: cd: /home/ubuntu/.memos: No such file or directory
```

### Steps to reproduce

Use configuration:
```
version: "3.0"
services:
  memos:
    image: ghcr.io/usememos/memos:latest
    container_name: memos
    volumes:
      - ~/.memos/:/var/opt/memos
    ports:
      - 5230:5230
```

1. Start `docker-compose up -d`
2. Try to open folder `cd cd ~/.memos`
