### ISSUE TITLE
登录时服务器cpu和读写满负载

### ISSUE THREAD

**Issue by wayner6** [usememos/memos#2552]
### Describe the bug

隔一段时间需要重新验证登录，在登录后台时，无法进入新的页面，网站也无法打开，这时查看服务器负载情况，发现读写和cpu是满负载状态，需要重启服务器才能打开页面，这时登录就能成功登录

我的docker-compose.yaml文件:
```
version: "3"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memeos
    hostname: memeos
    ports:
      - "7264:5230"
    volumes:
      - ./.memos/:/var/opt/memos
    restart: always
```
docker版本:
`Docker version 24.0.4, build 3713ee1`
docker-compose版本：
`docker-compose version 1.29.2, build 5becea4c`

### Steps to reproduce

1.点击登录进入后台登录页面
2.输入账号密码
3.点击登录出现卡死、服务满负载现象

### Screenshots or additional context

在此页面登录时引发服务器满负载
![image](https://github.com/usememos/memos/assets/88063517/b33bf15b-3d66-4206-9fcd-fb98c5d7185e)
使用阿里云的服务监控如图
![Screenshot_2023-11-27-11-01-46-551_com alibaba aliyun](https://github.com/usememos/memos/assets/88063517/2ffb10e4-1920-41a7-a256-158c1bd6bb10)

**Comment by qwasdev** [comment]
+1，我也遇到几次，卡到 ssh 都进不了，应该不是登录页的问题。😮

**Comment by qwasdev** [comment]
找到一个解决方案，在 docker-compose 配置 resources 限制容器的资源占用。

有待观察~

```yml
version: "3"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memeos
    hostname: memeos
    ports:
      - "7264:5230"
    volumes:
      - ./.memos/:/var/opt/memos
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
```

![image](https://github.com/usememos/memos/assets/134053124/96dd08fb-5e1d-44b2-836d-6036200a6ded)
