### ISSUE TITLE
Could not login memos behind reverse proxy (traefik)

### ISSUE THREAD

**Issue by xinfli** [usememos/memos#2617]
### Describe the bug

Could not login memos behind reverse proxy with `traefik`, error below can be found in web console:
```
Is there any workaround for this problem? I updated to latest version (0.18.0) but still get same error:

ClientError: /memos.api.v2.AuthService/GetAuthStatus UNKNOWN: Response stream closed without gRPC status. This may indicate a misconfigured CORS policy on the server: Access-Control-Expose-Headers must include "grpc-status" and "grpc-message".
    ct https://memos.x2log.net/assets/index-1fac1b39.js:299
    ClientError https://memos.x2log.net/assets/index-1fac1b39.js:299
    makeCall https://memos.x2log.net/assets/index-1fac1b39.js:300
```

Login with direct URL `http://<hostname>:5230` works.

Below is my docker compose for memos, it worked before, not sure when it started failing (I set all docker containers updated automatically):
```yaml
version: '3'

services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    networks:
      - traefik
    restart: unless-stopped
    ports:
      - ${Http_Port}:5230
    volumes:
      - ${Data_Folder}:/var/opt/memos
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik

      # Services and middlewares
      - traefik.http.services.memos.loadbalancer.server.port=5230
      - traefik.http.middlewares.memos-stripprefix.stripprefix.prefixes=/${Url_Prefix}

      # Routers for http
      - traefik.http.routers.memos-http.service=memos
      - traefik.http.routers.memos-http.entrypoints=http
      - traefik.http.routers.memos-http.rule=Host(`${DomainName}`)
      - traefik.http.routers.memos-http.middlewares=memos-stripprefix

      # Routers for https
      - traefik.http.routers.memos-https.service=memos
      - traefik.http.routers.memos-https.entrypoints=https
      - traefik.http.routers.memos-https.rule=Host(`${DomainName}`)
      - traefik.http.routers.memos-https.middlewares=memos-stripprefix
      - traefik.http.routers.memos-https.tls.certresolver=letsEncrypt

networks:
  traefik:
    external: true
```

### Steps to reproduce

1. Open memos login page http://memos.<domainname>, which is processed by `traefik`
2. Open web console of browser
3. Input username and password, click `login`

Login page will blocked on loading, error `Response stream closed without gRPC status` found in web console.

### Screenshots or additional context

Found [a similar issue](https://github.com/usememos/memos/issues/2263), but it's closed without any solution/workaround.

**Comment by loryncien** [comment]
do not use gRPC, stripprefix.

```yaml
---
version: "3"
services:
  memos:
    container_name: memos
    image: 'ghcr.io/usememos/memos:0.18.0'
    # image: 'ghcr.io/usememos/memos:test'
    expose:
      - "5230"
    # ports:
    #   - "5230:5230"
    volumes:
      - $DOCKERDIR/appdata/memos/data:/var/opt/memos
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## Middlewares - redirect-https|chain-authelia|chain-no-auth|chain-basic-auth
      ## HTTP Routers
      - "traefik.http.routers.$SERVER-web.entrypoints=web"
      - "traefik.http.routers.$SERVER-web.rule=Host(`memos.$DOMAINNAME`)"
      - "traefik.http.routers.$SERVER-web.middlewares=redirect-https@file"
      ## HTTPS Routers
      - "traefik.http.routers.$SERVER-websecure.entrypoints=websecure"
      - "traefik.http.routers.$SERVER-websecure.rule=Host(`memos.$DOMAINNAME`)"
      - "traefik.http.routers.$SERVER-websecure.middlewares=chain-no-auth@file"
      - "traefik.http.routers.$SERVER-websecure.service=$SERVER-svc"                # (Optional)
      - "traefik.http.routers.$SERVER-websecure.tls.certresolver=myresolver"
      ## HTTP Services
      - "traefik.http.services.$SERVER-svc.loadbalancer.server.port=5230"            # (Optional)

networks:
  default:
    name: traefik
    external: true
```
