### ISSUE TITLE
SSO using Authelia

### ISSUE THREAD

**Issue by tamimology** [usememos/memos#2670]
### Describe the bug

I have setup my Authelia for the SSO authentication, below is a screenshot of the config in Memos instance
![image](https://github.com/usememos/memos/assets/90429593/057cecc4-96f1-4fee-9bb7-55da3117aa43)

This is the Authelia configuration.yml
```
      - id: memos
        description: Memos
        secret: yM************************N6K...
        authorization_policy: two_factor
        redirect_uris:
          - https://memos.*********.com/auth/callback
        scopes:
          - openid
```

### Steps to reproduce

All mentioned above

### The version of Memos you're using

0.18.1

### Screenshots or additional context

This is after I login using my usual Authelia credentials (username and password and then I pass through the PIN using my Google Authenticator) 

![image](https://github.com/usememos/memos/assets/90429593/2df3badf-b098-44db-b448-340e5025e3c0)
