### ISSUE TITLE
Postgres, failed to upsert memo relation, internal=pq: column "version" does not exist. memos v0.18.1, postgres 15

### ISSUE THREAD

**Issue by bin16** [usememos/memos#2687]
### Describe the bug

Memos v0.18.1, PostgreSQL 15 

Failed to create memo with references (OR update memo with referneces), got error

``` json
{
  "error": "code=500, message=Failed to upsert memo relation, internal=pq: column \"version\" does not exist",
  "message": "Failed to upsert memo relation"
}

```

### Steps to reproduce

1. Setup memos (0.18) with postgres (v15 is tested), my docker-compose.yml is attached, see Screenshots or additional context
2. Sign in and go to home page
3. Type some words in the text box. 
4. Click on the <link icon> to add references, in the pop up window, input another memo's id (the memo exists)
5. Click on the <check mark icon>, linked memo's detail appears below the input box, that's good.
6. Close the popup window, and click the save button to create the new memo with reference. You may want to open the browser console to catch the network request.
7. In my test, it partially failed. Memo is created, but reference not added. Got a toast message "Failed to upsert memo relation".

### The version of Memos you're using

v0.18.1

### docker-compose.yml

``` yml
version: "3.0"
services:
  memos:
    image: ghcr.io/usememos/memos:latest
    container_name: memos
    env_file:
      - .env
    environment:
      - MEMOS_DRIVER=postgres
      - MEMOS_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    volumes:
      - ./memos/:/var/opt/memos
    ports:
      - 5230:5230
    depends_on:
      - db
  db:
    container_name: memos_postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - memos-pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  memos-pgdata:
```

### .env

``` env
POSTGRES_DB=memos
POSTGRES_USER=memos
POSTGRES_PASSWORD=yourpassword
```

#### curl

``` sh
curl 'https://XXXXXX/api/v1/memo' -X POST -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: zh-CN,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Referer: https://XXXXXX' -H 'Origin: https://XXXXXX' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Connection: keep-alive' -H 'Cookie: memos.access-token=XXXXXX' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers' --data-raw '{"content":"test reference #test ","visibility":"PRIVATE","resourceIdList":[],"relationList":[{"memoId":-1,"relatedMemoId":168,"type":"REFERENCE"}]}'
```

#### request body

``` json
{
    "content": "test reference #test ",
    "visibility": "PRIVATE",
    "resourceIdList": [],
    "relationList": [
        {
            "memoId": -1,
            "relatedMemoId": 160,
            "type": "REFERENCE"
        }
    ]
}
```

#### response

``` json
{
  "error": "code=500, message=Failed to upsert memo relation, internal=pq: column \"version\" does not exist",
  "message": "Failed to upsert memo relation"
}
```
