### ISSUE TITLE
docker 0.19.0 (stable) 升级后无法加载 memos, 并且内存异常

### ISSUE THREAD

**Issue by Lincest** [usememos/memos#2866]
### Describe the bug

docker 0.19.0 (stable) 升级后无法加载 memos, 并且内存异常.

docker compose 配置如下: 

```yml
version: '3'
services:
  memos:
    logging:
      options:
        max-size: "20m"
        max-file: "3"
    image: ghcr.io/usememos/memos:stable
    restart: always
    ports:
      - "5230:5230"
    volumes:
      - ./memos/:/var/opt/memos
```

在日志中没有捕获任何相关的错误信息, 但首页会一直显示memos加载中, 并且内存频繁到达 16G 的上限

(日志显示数据库 migrate 是成功的)

恢复到 0.18.2 版本后正常.

### Steps to reproduce

1. 从0.18.2 升级到 stable
2. 重启docker

### The version of Memos you're using

stable
