### ISSUE TITLE
Downgrade from v0.21.0 to v0.20.1 breaks app with uncaught error

### ISSUE THREAD

**Issue by joweich** [usememos/memos#3140]
### Describe the bug

As advised in the [v0.19.0 release notes](https://github.com/usememos/memos/releases/tag/v0.19.0), I migrated the `latest` docker image tag to `stable`. 
This downgrades my `v0.21.0` to `v0.20.1`.
However, the app won't load anymore while displaying _"fetching data..."_.
The browser console throws:

> Uncaught (in promise) ClientError: /memos.api.v2.MemoService/ListMemos INTERNAL: failed to list memos

Going back to the `latest` tag and thus `v0.21.0` fixes the issue.

Docker compose setup:
```
memos:
  image: neosmemo/memos:stable
  container_name: memos
  volumes:
    - ~/.memos/:/var/opt/memos
  ports:
    - 5230:5230
```

### Steps to reproduce

1. Use `v0.21.0`
2. Downgrade to `v0.20.1`
3. Load app

### The version of Memos you're using

0.20.1
