### ISSUE TITLE
User Choosing the Starting Day of the Week

### ISSUE THREAD

**Issue by noxonad** [usememos/memos#3219]
### Describe the solution you'd like

By default the calendar in the timeline sections starts with Sunday and there's no easy way to change that. A good part of the people start their week with Monday, or even Saturday. The UI should let each user decide what's their personal preferences.

### Type of feature

User Interface (UI)

### Additional context

As a temporary fix for the people who want to start their week with Monday, I came up with the following solution:

In the Settings > System you can add additional css code. Enter the following and click save: 
```css
.grid-cols-7 { grid-template-columns: repeat(6,minmax(0,1fr)); }
.grid-cols-7 > div:first-of-type {
  grid-column-start: -1;
}
```

If you want your week to start with Saturday instead of Monday, insert just:
```css
.grid-cols-7 > div:first-of-type {
  grid-column-start: 2;
}
```
