### ISSUE TITLE
S3 Storage can't be used

### ISSUE THREAD

**Issue by lhchong** [usememos/memos#3397]
### Describe the bug

为什么endpoint地址前会自动增加bucket?
- 我使用私有化部署的minio，endpoint填写的ip地址，但后台请求的s3地址却是   http://bucket.192.168.xxx.xxx 
- 我尝试在路由器网关 或 docker启动配置中设定一个自定义hosts，这样可以临时解决，但这并不合理

感谢开发者开源这个项目，我当前仍在使用 v0.21版本，希望可以修复s3相关配置；
如果是我的使用方式不对，请告知我正确的用法，谢谢；

![image](https://github.com/usememos/memos/assets/34005860/6c4da39e-5408-4a25-b72b-b3ef4db86441)

![image](https://github.com/usememos/memos/assets/34005860/d080f3c1-7593-42e0-b632-58f311f29cb7)

### Steps to reproduce

1. 部署并启动memos，注册一个账号
```yaml
services:
  usememos:
    image: 'neosmemo/memos:0.22'
    network_mode: 'host'
    environment:
      - MEMOS_DRIVER=mysql
      - MEMOS_DSN=root:123456@tcp(192.168.100.10:33608)/memos_v1
    volumes:
      - './data/:/var/opt/memos'
    ports:
      - '5230:5230'
    container_name: memos
    #restart: always
```
1. 配置s3存储，将endpoint填写为ip地址
3. 在home页上传一个附件，稍等片刻会提示错误

### The version of Memos you're using

v0.22
