### ISSUE TITLE
Problems with using Cloudflare Tunnels

### ISSUE THREAD

**Issue by vk2r** [usememos/memos#3512]
### Describe the bug

What's up !

I've been looking for a project like Memos to implement my notes, however I have encountered a problem. When using Cloudflare Tunnels to assign a securised public URL, it seems that Memos prevents me from resolving the URL correctly, because when I use the internal IP, it opens without any problem.

I use Cloudflared to redirect my internal IP's to the outside along with my domain without problems with other services, but I can't do it correctly with Memos.

Is there any special configuration to be done?

### Steps to reproduce

1. Implements Memos with Docker Compose script
2. Implements Cloudflared to localize internal's IP
3. Set static IP in router to redirect Memos
4. Configure Clouflare Tunnels with Cloudflared to redirect public IP to local IP

### The version of Memos you're using

0.22.1

**Comment by starsyork** [comment]
same issue

**Comment by jd-apprentice** [comment]
Hey! I'm also using tunnels here, my configuration is something like this

```yml
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: always
    volumes:
      - ./memos/:/var/opt/memos
    ports:
      - 5230:5230
    networks:
      lan:
         ipv4_address: 10.5.0.10

networks:
  lan:
   ipam:
    config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1
```

![image](https://github.com/usememos/memos/assets/68082746/e8c203b8-aa5b-4de4-a68f-7769b8834d01)

This assuming the container is running in the same machine as the tunnel, in case they are in different machies as I can see you can use <IP-MACHINE>:<PORT> (if they are in the same network)

**Comment by starsyork** [comment]
With Cloudflare tunnel settings, I am able to access my Synology Nas home at `localhost:5000`, but I encounter a 404 error when trying to access `localhost:5230`

**Comment by albert7617** [comment]
Works with following config:

<img width="195" height="364" alt="Image" src="https://github.com/user-attachments/assets/e99db245-f477-4ed3-a330-25cb1166bd67" />

docker-compose.yml
```
services:
  memo:
    image: neosmemo/memos:stable
    container_name: memos
    ports:
      - "5230:5230"
    volumes:
      - ./memos/:/var/opt/memos
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - memo
    restart: unless-stopped
```
