### ISSUE TITLE
Is it possible to provide a tutorial for data backup or migration?

### ISSUE THREAD

**Issue by eMUQI** [usememos/memos#3910]
### Describe the solution you'd like

I have checked the issue list, and the developers have clearly stated that memos will not offer a backup or export function. I understand that this is an open-source project, and the author is free to decide whether to adopt suggestions from the community.  
#3843  #3802 #2636 #2965

Now, I'm wondering if anyone can provide a tutorial on how to export all records stored in memos. I hope to export the data and deploy memos on a new device. If direct implementation isn't possible, I'd appreciate any method that can save the data locally.

Below is my configuration file path, but there's no data under `~/Docker/memos/data`.

```
version: "3.0"
services:
  memos:
    image: neosmemo/memos:stable
    restart: unless-stopped
    container_name: memos
    volumes:
      - ~/Docker/memos/data/:/var/opt/memos
    ports:
      - 80:5230
```

### Type of feature

Documentation
