### ISSUE TITLE
Better display of media resources such as images and videos

### ISSUE THREAD

**Issue by aliuq** [usememos/memos#4296]
### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/cced76b5-c138-443c-bf70-4c84f6ca8bc0)

Hope to use grid to better adapt to media resources

There is no special class used to identify a certain page, which causes the custom css selector to affect all pages

### Type of feature

User Interface (UI)

### Additional context

custom style, I can't make it only take effect on the home page and not the `/resources` page.

```css
main > section > div > div > div:nth-child(2) > div > div:has(video),
main > section > div > div > div:nth-child(2) > div > div:has(img) {
  display: grid;
  grid-template-columns: repeat(4,minmax(0,1fr));
  gap: 0.25rem;
}

main > section > div > div > div:nth-child(2) > div > div:has(video) > *,
main > section > div > div > div:nth-child(2) > div > div:has(img) > * {
  aspect-ratio: 1 / 1;
  border-radius: 0.5rem;
}

main > section > div > div > div:nth-child(2) > div > div:has(video) video {
  object-fit: cover;
}
```
