### ISSUE TITLE
doesn't work...

### ISSUE THREAD

**Issue by vigo** [usememos/memos#4310]
### Describe the bug

my docker stack:

```yml
services:
  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - "memos_postgres_data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: memos
      POSTGRES_PASSWORD: ${MEMOS_DB_PASSWD}
      POSTGRES_DB: memosdb
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - memos_net

  memos:
    image: neosmemo/memos:stable
    restart: always
    depends_on:
      - db
    ports:
      - 5230:5230
    environment:
      - MEMOS_DRIVER=postgres
      - MEMOS_DSN=${MEMOS_DATABASE_URL_MIGRATION}
    networks:
      - traefik_net
      - memos_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memos.rule=Host(`****`)"
      - "traefik.http.routers.memos.entrypoints=websecure"
      - "traefik.http.routers.memos.tls=true"
      - "traefik.http.routers.memos.tls.certresolver=****"
      - "traefik.http.routers.memos.middlewares=auth"
      - "traefik.http.services.memos.loadbalancer.server.port=5230"
      - "traefik.docker.network=traefik_net"

networks:
  traefik_net:
    external: true
  memos_net: null

volumes:
  memos_postgres_data: null

```

service logs

```
memos_memos.1.zkb3p0tgq2ex@srv649579    | driver: postgres
memos_memos.1.zkb3p0tgq2ex@srv649579    | ---
memos_memos.1.zkb3p0tgq2ex@srv649579    | Version 0.23.0 has been started on port 5230
memos_memos.1.zkb3p0tgq2ex@srv649579    | ---
memos_memos.1.zkb3p0tgq2ex@srv649579    | See more in:
memos_memos.1.zkb3p0tgq2ex@srv649579    | 👉Website: https://usememos.com
memos_memos.1.zkb3p0tgq2ex@srv649579    | 👉GitHub: https://github.com/usememos/memos
memos_memos.1.zkb3p0tgq2ex@srv649579    | 2025/01/24 11:40:27 INFO client error method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
memos_memos.1.zkb3p0tgq2ex@srv649579    | 2025/01/24 11:40:27 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
memos_memos.1.zkb3p0tgq2ex@srv649579    | 2025/01/24 11:40:36 INFO client error method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
memos_memos.1.zkb3p0tgq2ex@srv649579    | 2025/01/24 11:40:36 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
memos_memos.1.zkb3p0tgq2ex@srv649579    | 2025/01/24 11:41:51 INFO client error method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
memos_memos.1.zkb3p0tgq2ex@srv649579    | 2025/01/24 11:41:51 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"

```

app runs, but service has errors...
<img width="819" alt="Image" src="https://github.com/user-attachments/assets/c49a4774-ebb4-46a5-994a-49babced8c89" />

### Steps to reproduce

Just deployed and got service errors... 

### The version of Memos you're using

stable
