### ISSUE TITLE
How to reverse proxy with custom url path?

### ISSUE THREAD

**Issue by Chocobo-ts** [usememos/memos#436]
I try to get access to memos on custom url path with nginx proxy_pass (https://somedomain.xyz/memos)

```
        location /memos {
            proxy_pass http://127.0.0.1:5230$request_uri;
        }
```

but all requests like a _/sw.js_  failed with 404, because it calls root url instead my path _/memos/sw.js_
![2022-11-09_20-20](https://user-images.githubusercontent.com/31732478/200897791-fb5d731a-98c0-45a2-871d-d6b61248730e.png)

How can i use memos behind a reverse proxy?

**Comment by boojack** [comment]
I think a better way is using the subdomain like 'memos.domain.xyz' but not 'domain.xyz/memos'.

**Comment by sudOnur** [comment]
Hi, you can use this docker compose file to have a reverse proxy setup.

```
version: "3.0"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - ./db/:/var/opt/memos
    ports:
      - 5230:5230
    environment:
      - VIRTUAL_HOST=memos.local
      - VIRTUAL_PORT=5230
```

And edit /etc/hosts file if you are in a local development environment. Or just point your domain to server IP.
