### ISSUE TITLE
Code Blocks auto word wrap

### ISSUE THREAD

**Issue by N4v41** [usememos/memos#4389]
### Describe the solution you'd like

it would be great if there was a config option to auto break lines on code blocks, currently it puts a scroll i would like it to show all the code without the scroll.

### Type of feature

User Interface (UI)

### Additional context

show more

**Comment by lhuanyun** [comment]
You can change the display by adding css styles in the system. I think it is better to display all.

**Comment by N4v41** [comment]
Thanks, didn't thought this way, i will try to do it

**Comment by N4v41** [comment]
thanks @lhuanyun that worked ! 

in case anyone needs something like this, i really dont know CSS so I used this that was generated by an LLM:
```CSS
/* Code Block CSS */
pre, code {
    white-space: pre-wrap; /* make text break line */
    word-wrap: break-word; /* log words also break lines */
    padding: 10px; /* internal spacing */
    border-radius: 5px; /* round borders */
    font-family: monospace; /* monospace font for the codeblock */
    font-size: 14px; /* font size */
    line-height: 1.5; /* line spacing */
    overflow: auto; /* allow roll if necessáry  */
}
```
