### ISSUE TITLE
healthcheck endpoint

### ISSUE THREAD

**Issue by richie-tt** [usememos/memos#4498]
### Describe the solution you'd like

Hello,

First of all, thank you for the great application. I started using it and love it. 

I would like to ask you to implement a proper endpoint to check the status of the Memos application. Such an endpoint should return `200 OK` if the application is working correctly, has access to the database, etc.
In case of any problem, a code should be returned between `4xx` and `5xx`, depending on the issue.

Status code is required for API gateways like Traefik to determine if the service is ready to receive traffic.

Example of Traefik healtcheck [config](https://doc.traefik.io/traefik/routing/services/#health-check_1)

```yaml
http:
  services:
    app:
      weighted:
        healthCheck: {}
        services:
        - name: appv1
          weight: 3
        - name: appv2
          weight: 1

    appv1:
      loadBalancer:
        healthCheck:
          path: /status
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://private-ip-server-1/"

    appv2:
      loadBalancer:
        healthCheck:
          path: /status
          interval: 10s
          timeout: 3s
        servers:
        - url: "http://private-ip-server-2/"
```

### Type of feature

User Interface (UI)
