### ISSUE TITLE
Show all content instead of "show more"?

### ISSUE THREAD

**Issue by binarydad** [usememos/memos#4534]
### Describe the solution you'd like

I love the UI update in 0.24.1, but would love it if there could be an option to always show all the post content, instead of truncating it with a "Show more" button. I typically have long posts and need to quickly view them while scrolling. I feel this was an option before the update but may have gotten lost?

Appreciated. Thanks!

![Image](https://github.com/user-attachments/assets/b27e8ab4-3c0e-4bb6-a241-6e2a1cbb52c3)

### Type of feature

User Interface (UI)

**Comment by glwhappen** [comment]
It would be nice to be able to control the folding of each memo individually, for example to mimic the <! --more--> in hexo, which would then collapse from this position

**Comment by icheer** [comment]
I removed this "Show more" feature by customized CSS anyway...
'Cause I don't like these MORE buttons appear here and there, especailly often in mobile device


```CSS
/* Remove: line-clamp 6 */
.group > .justify-start .line-clamp-6 {max-height: 72rem; -webkit-line-clamp: 36}
.group > .justify-start .line-clamp-6 .bg-gradient-to-b {background: none}
.group > .justify-start .line-clamp-6 + .mt-1 {display: none}
```

**Comment by wzzrd** [comment]
Oh damn! Love that! Might try out the new release again (I reverted back to 0.24.0 after the changes).

You just the drop the above code verbatim into the "Additional CSS" text area, @icheer?

**Comment by icheer** [comment]
Yeah, right. @wzzrd 
Glad to hear you like it.
I wrote some more Additional CSS in fact.
Paste them to here, share with you and other guys.
(I write comments to let you understand their targets as much as I can)

```CSS
/* modify background color to let the cards display more obviously */
html:not(.dark) > body {background-color: rgb(244, 244, 244)}

/* sidebar: modify the top-left icon, the png is from my private memo's resources */
header .relative {cursor: pointer}
#header-auth {opacity: 0; transition: all 0.15s}
#header-auth:hover {opacity: 1}
header .shrink img[decoding] {display: block; content: url("/file/resources/RwMNkvDrTBUPd3eMd2CmXP/1.png")}

/* memos */
.group p:not([hidden]) + p:not([hidden]) {margin-top: 0.75rem}
textarea {resize: vertical !important}
.mb-2 ~ .group {margin-top: 0.85rem}
.group hr {margin: 1rem 0 !important}

/* re-design the #tag's style */
span.inline-block.text-blue-600 {display: inline-flex; padding: 0 8px; justify-content: center; align-items: center; border-radius: .375rem; background: #0d9488b3; color: #f3f4f6; font-size: 0.8em;}

/* remove: line-clamp 6 */
.group > .justify-start .line-clamp-6 {max-height: 72rem; -webkit-line-clamp: 36}
.group > .justify-start .line-clamp-6 .bg-gradient-to-b {background: none}
.group > .justify-start .line-clamp-6 + .mt-1 {display: none}
```
