### ISSUE TITLE
Syntax highlighter not work

### ISSUE THREAD

**Issue by tealaforgia** [usememos/memos#4605]
### Describe the bug

Since version 0.24.1 syntax highlighting in code blocks no longer works. Now the text is always displayed in black. In previous versions and in the canary build syntax highlighting works.

### Steps to reproduce

- Create docker container with this docker-compose.yaml:
```
version: '3'

services:
  memos:
    image: neosmemo/memos:"VERSION"
    container_name: memos
    hostname: memos
    ports:
      - "PORT":5230
    restart: unless-stopped
```

- Open the WebUI and create an account

- Create a note with this content:
```
'''javascript
const x = 1;
const y = 2;
const z = 3;
'''
```
(use ` instead of ')

### The version of Memos you're using

0.24.2

### Screenshots or additional context

![Image](https://github.com/user-attachments/assets/efddbb47-5e8d-41c9-a4ab-1396955428d8)
