### ISSUE TITLE
Offline capabilities to Memos

### ISSUE THREAD

**Issue by Cadavanaugh** [usememos/memos#4684]
### Describe the solution you'd like

It would be interesting if when we lost internet connection we still had the app running normally doing local changes and then when back online sync thoses changes with the server.

### Type of feature

User Experience (UX)

### Additional context

This video might help with the development https://www.youtube.com/watch?v=1FMkFc4TIio

**Comment by asavageiv** [comment]
I took a stab at this, but it is complicated by the fact that Memos uses gRPC-Web. gRPC-Web uses POST requests for everything which can't be cached in the native Cache objects without some manipulation. It looks like the server already exposes a REST API, so maybe we could switch to that?

**Comment by asavageiv** [comment]
I tried generating an API client using `@openapitools/openapi-generator-cli` and the `openapi.yaml` but some of the methods don't work correctly. For example `GetWorkspaceSetting` should take a string like `"workspace/settings/GENERAL"` and make a request to `/api/v1/workspace/settings/GENERAL` but instead it makes a request to `/api/v1/workspace/workspace%2Fsettings%2FGENERAL/*`. Note the URL encoding and trailing `/*`.

It seems like an issue with how the proto definition is translated to openapi.yaml.
```proto3
  rpc GetWorkspaceSetting(GetWorkspaceSettingRequest) returns (WorkspaceSetting) {
    option (google.api.http) = {get: "/api/v1/{name=workspace/settings/*}"};
    option (google.api.method_signature) = "name";
  }
```
generates
```
/api/v1/workspace/{workspace}/*:
        get:
            tags:
                - WorkspaceService
            description: Gets a workspace setting.
            operationId: WorkspaceService_GetWorkspaceSetting
            parameters:
                - name: workspace
                  in: path
                  description: The workspace id.
                  required: true
                  schema:
                    type: string
```

Maybe a bug in [protoc-gen-openapi](https://github.com/google/gnostic/tree/main/cmd/protoc-gen-openapi)
