### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ItsNoted** [usememos/memos#521]
### Is your feature request related to a problem?

White is bright.

### Describe the solution you'd like

Make a dark mode for better visual experience when browsing in the dark or for those with sensitive eyes.

**Comment by Zeng1998** [comment]
Dark mode isn't supported yet, and I'm not sure if it is a high-priority need.

For now, you can try the following additional css (shared from the community)

```css
@media (prefers-color-scheme: dark) {
    html {
        filter: invert(90%) hue-rotate(180deg);
    }

    img, video, div[class*="language-"] {
        filter: invert(110%) hue-rotate(180deg);
        opacity: .8;
    }
}
```
