### ISSUE TITLE
Auth with OIDC

### ISSUE THREAD

**Issue by kernelkaribou** [usememos/memos#528]
### Is your feature request related to a problem?

I heavily use Authelia in my self hosted environment and try to use only services that can authenticate through HTTP Headers from the Reverse Proxy or OIDC.

### Describe the solution you'd like

Would be great to be able to authenticate through other methods such as OIDC or other remote auth options.

### Additional context

I am not an expert in this space, I know that other services like Octoprint or Paperless-ngx offer the ability to do authentication through HTTP header. Not sure how that works given you utilize an email for users.

**Comment by firestrife23** [comment]
+1 on OIDC

Check this out, if you're familiar with GO, i'm more of python guy tho not much of help lol.

https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc

This will allow authentication against any ODIC providers: google, auth0, keycloak, anthelia, authentic, etc.

**Comment by alfeg** [comment]
I would be happy to use auth proxy, like for example [how Grafana do](https://ilayk.com/2021/12/10/grafana-authentication-with-cloudflare-access) to be able to auth with Cloudflare Access

**Comment by peterbuga** [comment]
I can confirm this works with Authelia right now 👍

**Comment by Hobbabobba** [comment]
Working configuration for Authelia:

Server side (in `configuration.yml`): 
```
identity_providers:
  oidc:
    - id: memos
      description: memos
      secret: 'insertsecrethere'
      public: false
      authorization_policy: two_factor
      redirect_uris:
        - https://URL_OF_MEMOS/auth/callback
      scopes:
        - openid
        - profile
        - email
      grant_types:
        - authorization_code
      userinfo_signing_algorithm: none
```
client side (in memos):
| Field    | Value   | 
|--------------|-----------|
| `Name`    | `Authelia`   | 
| `Identifier Filter`    | | 
|  `Client ID`  | `memos`   |
|  `Client secret` | `insert_secret_here`   |
|  `Authorization endpoint`  | `https://auth.example.com/api/oidc/authorization`  |
|  `Token endpoint`  | `https://auth.example.com/api/oidc/token`   |
|  `User endpoint` |  `https://auth.example.com/api/oidc/userinfo`   |
|  `Scopes`  | `openid profile email`   |
|  `Identifier`  | `preferred_username`  |
|  `Display Name`  | `given_name`   |
|  `Email`  | `email` |
