### ISSUE TITLE
自定义js脚本执行时机不对

### ISSUE THREAD

**Issue by chaos-zhu** [usememos/memos#709]
### Describe the bug

在发布的memo中，习惯用【**双击**】来选词然后复制。

程序默认会进入到编辑模式，所以写了句js代码来屏蔽该功能。代码如下：

```js
document.querySelectorAll('.memo-content-wrapper ').forEach(item => item.style.pointerEvents = 'none') 
```

该js执行时机在memo列表还未加载出来就已经执行了，所以没有达到想要的效果。

改成css如下(有效)：
```css
.memo-content-wrapper {
  pointer-events: none;
}
```

### Steps to reproduce

自定义的js是不是应该等列表加载后再执行会好一点
