### ISSUE TITLE
建议对标签外观做一点优化

### ISSUE THREAD

**Issue by i-iooi-i** [usememos/memos#955]
### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/1827701/212521816-708662e7-ca6b-4a59-bd0f-d62987260dbe.png)

这是来自Obsidian上的一款Memos插件，它对标签做了单独的圆角高亮的外观处理。

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/1827701/212521878-dc6a4653-1914-472d-9782-4d92dfa9342d.png)

想请大佬考虑下Memos针对标签做如上优化的可行性。
目前的标签外观确实在视觉上对文字内容形成了一些干扰，若是能通过设计标签外观样式做以区分，应该会更好一些。

**Comment by fakerange** [comment]
设置里应该可以自定义CSS吧

**Comment by Wujiao233** [comment]
自定义CSS里添加下面的代码可以做到深浅色都兼容的类似的效果
```css
.dark .tag-span{
    border: 1px solid rgb(97,97,97);
    border-radius: 6px;
    background-color: rgb(97, 97, 97);
    font-size: 12px;
    padding: 0px 4px;
    color: rgb(231,231,231) !important;
}

.tag-span{
    border: 1px solid rgb(231,231,231);
    border-radius: 6px;
    background-color: rgb(231, 231, 231);
    font-size: 12px;
    padding: 0px 4px;
    color: rgb(97,97,97) !important;
}
```

**Comment by i-iooi-i** [comment]
> 自定义CSS里添加下面的代码可以做到深浅色都兼容的类似的效果
> 
> ```css
> .dark .tag-span{
>     border: 1px solid rgb(97,97,97);
>     border-radius: 6px;
>     background-color: rgb(97, 97, 97);
>     font-size: 12px;
>     padding: 0px 4px;
>     color: rgb(231,231,231) !important;
> }
> 
> .tag-span{
>     border: 1px solid rgb(231,231,231);
>     border-radius: 6px;
>     background-color: rgb(231, 231, 231);
>     font-size: 12px;
>     padding: 0px 4px;
>     color: rgb(97,97,97) !important;
> }
> ```

好棒，感谢，视觉效果一下变高级了。🥰

**Comment by Jonnyan404** [comment]
- css代码 (来源于官方群

```css
.memo-content-wrapper>.memo-content-text .tag-span {
    color: #5783f7;
    cursor: pointer;
    background-color: #eef3fe;
    padding: 4px;
    font-size: 15px;
    border-radius: 3px;
}
```

- 效果图

![image](https://user-images.githubusercontent.com/20352705/215329084-ba589db9-073a-413c-9b10-84be91bb1a15.png)
